### PR TITLE
Add support for range requests

### PR DESCRIPTION
**Pull request by olalonde**

### CODE REVIEW

**Comment by mafintosh** [comment]
you can already use range support using the `start` and `end` options. is that not good enough?

**Comment by mafintosh** [comment]
(we should however document that)

**Comment by olalonde** [comment]
Right, I implemented the same thing for https://github.com/jb55/s3-blob-store/issues/4 though so I can just use the same options for both modules.

**Comment by mafintosh** [comment]
Ah okay. Is there any reason the other module could't just use `start` and
`end` as well? We should standardize these option in abstract-blob-store as
well

**Comment by olalonde** [comment]
Yeah, would be nice to standardise. There's no particular reason I put them under `range`. I suppose one nice thing about it is that you can just do `if (opts.range) {` whereas if we put them under `opts.start` and `opts.end`, an implementer might mistakenly use `if (opts.start) {` which should really be `if (opts.start !== undefined)` in case `opts.start === 0`. Another reason is that we could have an optional `range.type` which defaults to `bytes` though I'm not sure we really need that.

Anyways, I don't really mind as long as it's the same thing across blob stores...

**Comment by jb55** [comment]
Was there any consensus here? Should I merge https://github.com/jb55/s3-blob-store/issues/4 ?

**Comment by djblue** [comment]
I also opened up [mafintosh/content-addressable-blob-store#4](https://github.com/mafintosh/content-addressable-blob-store/pull/4) to support range requests for blobs.

:+1:  for standardizing these option in abstract-blob-store.

**Comment by mafintosh** [comment]
@jb55 we're going for the opts.start, opts.end interface

**Pull request closed without merging**
